(()=>{const d=document.documentElement,a=document.getElementById('arBtn'),e=document.getElementById('enBtn'),lab=document.getElementById('labBox'),p=document.getElementById('personaBtn'),c=document.getElementById('calBtn'),meta=document.querySelector('meta[name=description]');function lang(x){x=x==='en'?'en':'ar';d.lang=x;d.dir=x==='ar'?'rtl':'ltr';a.setAttribute('aria-pressed',x==='ar');e.setAttribute('aria-pressed',x==='en');document.title=x==='ar'?'خداع الأنسنة — الحشو وتقمّص الشخصية':'The Anthropomorphism Deception — filler and performed personality';meta.content=x==='ar'?'دليل عربي وإنجليزي يشرح الحشو وتقمّص الشخصية في واجهات الذكاء الاصطناعي.':'A bilingual guide to filler, performed personality, and calibrated human-system interaction.';try{localStorage.setItem('khz-lang',x)}catch(_){}}a.onclick=()=>lang('ar');e.onclick=()=>lang('en');let saved='ar';try{saved=localStorage.getItem('khz-lang')||'ar'}catch(_){}lang(saved);function mode(x){lab.dataset.mode=x;p.setAttribute('aria-pressed',x==='persona');c.setAttribute('aria-pressed',x==='calibrated')}p.onclick=()=>mode('persona');c.onclick=()=>mode('calibrated');const bar=document.getElementById('progress');function progress(){const x=d.scrollHeight-d.clientHeight;bar.style.width=(x?d.scrollTop/x*100:0)+'%'}addEventListener('scroll',progress,{passive:true});progress();if('IntersectionObserver'in window&&!matchMedia('(prefers-reduced-motion:reduce)').matches){const o=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('seen');o.unobserve(x.target)}}),{threshold:.07});document.querySelectorAll('.reveal').forEach(x=>o.observe(x))}else document.querySelectorAll('.reveal').forEach(x=>x.classList.add('seen'))})();

(()=>{
'use strict';
const root=document.documentElement,$=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>Array.from(c.querySelectorAll(s)),clamp=n=>Math.max(0,Math.min(100,n));
const samples={ar:{filler:'أنا أفهم تمامًا قلقك، وبكل تأكيد هذا التقرير مميز جدًا ومهم للغاية. من الجدير بالذكر أنه يقدم رؤية شاملة ومتعمقة، وفي نهاية المطاف يمكنك الاعتماد عليه لأنه يبدو احترافيًا وواضحًا.',calibrated:'بحسب الصفحة 12 من التقرير، يذكر النص ثلاثة مراجع. لم أتحقق من صلاحية الروابط أو صحة البيانات، لذلك لا يمكنني تأكيد موثوقية الاستنتاج قبل مراجعة المصادر والمنهج والاختبار.'},en:{filler:'I completely understand your concern. This is absolutely a highly important and remarkably comprehensive report. It is important to note that it offers a robust, deeply insightful perspective, so you can confidently rely on it.',calibrated:'According to page 12, the report lists three references. I did not verify the links or underlying data, so I cannot confirm the conclusion until the sources, method, and tests are checked.'}};
const lex={ar:{filler:['بشكل عام','من المهم أن نلاحظ','من الجدير بالذكر','في نهاية المطاف','في هذا السياق','بكل تأكيد','بلا شك','لا شك أن','يمكن القول','في الواقع','بطبيعة الحال','مميز جدًا','مهم للغاية','رؤية شاملة','متعمقة','احترافيًا وواضحًا','يمكنك الاعتماد'],persona:['أنا أفهم تمامًا','أنا أفهم','أشعر','يسعدني','أنا هنا من أجلك','أهتم','أعدك','صدقني','من خبرتي','أنا واثق','أنا متأكد','كصديق','يمكنك الوثوق','يمكنك الاعتماد'],evidence:['مصدر','المصادر','مرجع','مراجع','وفقًا','بحسب','بيانات','رابط','الروابط','دراسة','تحقق','أتحقق','اختبار','تجربة','اقتباس','تاريخ','صفحة','منهج','رقم','سجل']},en:{filler:['generally speaking','it is important to note','it is worth noting','at the end of the day','in this context','absolutely','certainly','without a doubt','highly important','remarkably comprehensive','robust','deeply insightful','professional and clear','you can confidently rely'],persona:['i completely understand','i understand','i feel','i am here for you',"i'm here for you",'i care','i promise','trust me','in my experience','i am confident',"i'm confident",'i am certain',"i'm certain",'as your friend','you can trust','you can rely'],evidence:['source','sources','reference','references','according to','data','link','links','study','verify','verified','test','tested','experiment','citation','date','page','method','record','audit']}};
const input=$('#fillerInput'); if(!input)return;
let edited=false; input.addEventListener('input',()=>edited=true);
function lang(){return root.lang==='en'?'en':'ar'}
function esc(s){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function reg(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function count(t,arr){const n=t.toLocaleLowerCase();return arr.reduce((a,p)=>a+((n.match(new RegExp(reg(p),'giu'))||[]).length),0)}
function tokens(t){return t.toLocaleLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim().split(/\s+/u).filter(Boolean)}
function repetition(ts){if(ts.length<3)return 0;const m=new Map;for(let i=0;i<ts.length-1;i++){const b=ts[i]+' '+ts[i+1];m.set(b,(m.get(b)||0)+1)}let r=0;m.forEach(v=>{if(v>1)r+=v-1});return r/Math.max(1,ts.length-1)}
function analyse(t){const l=lang(),x=lex[l],ts=tokens(t),words=ts.length,f=count(t,x.filler),p=count(t,x.persona),e=count(t,x.evidence),rep=repetition(ts),nums=(t.match(/\b\d+(?:[.,]\d+)?\b/g)||[]).length,links=(t.match(/https?:\/\/\S+/gi)||[]).length,unique=words?new Set(ts).size/words:1,first=l==='ar'?ts.filter(w=>['أنا','أفهم','أرى','أعتقد','أشعر','واثق','متأكد'].includes(w)).length:ts.filter(w=>['i','me','my','understand','believe','feel','confident'].includes(w)).length;return{words,f,p,e,fs:clamp(Math.round(f*14+rep*95+Math.max(0,.73-unique)*60)),ps:clamp(Math.round(p*16+(words?first/words:0)*170)),es:clamp(Math.round(e*12+nums*5+links*22))}}
function mark(t){let items=[];['filler','persona','evidence'].forEach(k=>lex[lang()][k].forEach(p=>items.push({p,k})));items.sort((a,b)=>b.p.length-a.p.length);let out=esc(t);items.forEach(({p,k})=>{out=out.replace(new RegExp(reg(esc(p)),'giu'),m=>`<mark class="mark-${k}">${m}</mark>`)});return out}
function setRing(id,v){const el=$(id);el.style.setProperty('--score',v);el.querySelector('span').textContent=v}
function run(){const t=input.value.trim(),r=analyse(t);setRing('#fillerRing',r.fs);setRing('#personaRing',r.ps);setRing('#evidenceRing',r.es);$('#fillerDetail').textContent=lang()==='ar'?`${r.f} عبارة عامة · ${r.words} كلمة`:`${r.f} generic cues · ${r.words} words`;$('#personaDetail').textContent=lang()==='ar'?`${r.p} إشارة شخصية`:`${r.p} persona cues`;$('#evidenceDetail').textContent=lang()==='ar'?`${r.e} إشارة تحقق`:`${r.e} verification cues`;let msg;if(!t)msg=lang()==='ar'?'أدخل نصًا للتحليل.':'Enter text to analyze.';else if(r.fs>=65&&r.es<30)msg=lang()==='ar'?'إشارة قوية إلى كلام عام بلا ارتكاز كافٍ على مصدر أو اختبار. اختصره واسأل: ما الحقيقة الجديدة؟ وما الذي يثبتها؟':'Strong signal of generic language with little source or test grounding. Ask: what new fact was added, and what verifies it?';else if(r.ps>=55)msg=lang()==='ar'?'النبرة تبني شخصية واضحة. افصل دفء الأسلوب عن دقة الادعاء.':'The tone constructs a strong persona. Separate conversational warmth from claim accuracy.';else if(r.es>=55)msg=lang()==='ar'?'النص يذكر حدودًا أو مصادر أو اختبارًا. هذه بداية أفضل، لكنها لا تغني عن فحص الدليل نفسه.':'The text names limits, sources, or tests. That is better, but the evidence still needs inspection.';else msg=lang()==='ar'?'الإشارات مختلطة. لا تحكم من الأسلوب وحده؛ ابحث عن حقيقة محددة ومصدر واختبار وحدود معلنة.':'Signals are mixed. Do not judge by style alone; look for specific facts, sources, tests, and stated limits.';$('#analysisSummary').textContent=msg;$('#analysisPreview').innerHTML=mark(t)||'—'}
$$('[data-sample]').forEach(b=>b.addEventListener('click',()=>{input.value=samples[lang()][b.dataset.sample];edited=false;run()}));$('#analyzeBtn').addEventListener('click',run);
document.addEventListener('click',e=>{if((e.target.closest('#arBtn')||e.target.closest('#enBtn'))&&!edited){setTimeout(()=>{input.value=samples[lang()].filler;run();renderPersona()},0)}});run();
const ranges={warmth:$('#warmthRange'),certainty:$('#certaintyRange'),persona:$('#personaRange')},values={warmth:$('#warmthValue'),certainty:$('#certaintyValue'),persona:$('#personaValue')},presets={calibrated:[15,15,10],friend:[92,52,88],expert:[32,94,72],marketer:[72,96,76]};
function renderPersona(){const w=+ranges.warmth.value,c=+ranges.certainty.value,p=+ranges.persona.value;Object.keys(values).forEach(k=>values[k].value=ranges[k].value);const l=lang();let parts=[];if(l==='ar'){if(p>55)parts.push(c>75?'من خبرتي، أنا واثق من هذا التقييم.':'أنا أرى أن هذا التقييم معقول.');if(w>65)parts.push('أفهم لماذا يهمك هذا، وأنا هنا لأساعدك.');parts.push(c>75?'يمكنك الاعتماد على الاستنتاج؛ التقرير يبدو قويًا وواضحًا.':c>35?'يبدو الاستنتاج معقولًا، لكن الثقة به محدودة.':'حلّلت النص فقط، ولا أستطيع تأكيد الاستنتاج.');if(w>85)parts.push('اطمئن، سنمشي فيها خطوة بخطوة.')}else{if(p>55)parts.push(c>75?'In my experience, I am confident in this assessment.':'I believe this assessment is plausible.');if(w>65)parts.push('I understand why this matters, and I am here with you.');parts.push(c>75?'You can rely on the conclusion; the report appears strong and clear.':c>35?'The conclusion appears plausible, but confidence is limited.':'I analyzed the text only and cannot confirm the conclusion.');if(w>85)parts.push('Do not worry; we will take it one step at a time.')}$('#personaOutput').textContent=parts.join(' ');$('#factCore').textContent=l==='ar'?'المتاح: نص التقرير فقط. لم تُفحص المصادر أو البيانات خارجيًا.':'Available input: the report text only. Sources and data were not externally verified.';const mask=Math.round((w+c+p)/3);$('#maskLevel').textContent=`MASK ${mask}%`;$('#badgeWarmth').classList.toggle('on',w>45);$('#badgeCertainty').classList.toggle('on',c>45);$('#badgePersona').classList.toggle('on',p>45)}
Object.values(ranges).forEach(r=>r.addEventListener('input',()=>{$$('.preset').forEach(b=>b.classList.remove('active'));renderPersona()}));$$('.preset').forEach(b=>b.addEventListener('click',()=>{const v=presets[b.dataset.preset];[ranges.warmth.value,ranges.certainty.value,ranges.persona.value]=v;$$('.preset').forEach(x=>x.classList.toggle('active',x===b));renderPersona()}));renderPersona();
})();